source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'jwt'


group :development do
  gem 'sinatra-contrib'
end

gem "newrelic_rpm"
gem "oj"
gem "parallel"
gem "puma_worker_killer", require: false
gem "sentry-ruby"
gem "stackprof"

# 必要に応じて使う
gem "connection_pool"
gem "dalli"
# gem "redis"
# gem "sidekiq"
